(()=>{'use strict';
const K='horseEvaluator3',V='3.0.2',$=id=>document.getElementById(id);let state=load();
const E={yearFilter:$('yearFilter'),clubFilter:$('clubFilter'),stableAreaFilter:$('stableAreaFilter'),searchInput:$('searchInput'),sortSelect:$('sortSelect'),favoriteOnly:$('favoriteOnly'),dashboard:$('dashboard'),horseList:$('horseList'),resultCount:$('resultCount'),emptyState:$('emptyState'),horseDialog:$('horseDialog'),horseForm:$('horseForm'),detailDialog:$('detailDialog'),detailContent:$('detailContent'),toast:$('toast'),importUrlBtn:$('importUrlBtn'),importStatus:$('importStatus')};
function base(){return{version:V,app:'Horse Evaluator',horses:[],updatedAt:new Date().toISOString()}}
function uid(){return crypto.randomUUID?crypto.randomUUID():'h-'+Date.now()+'-'+Math.random().toString(16).slice(2)}
function t(v){return(v??'').toString().trim()} function n(v){return v===''||v==null?null:Number(v)}
function esc(v){return t(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function fmt(d){return d?new Intl.DateTimeFormat('ja-JP',{dateStyle:'medium',timeStyle:'short'}).format(new Date(d)):'―'}
function money(v){return v==null?'―':new Intl.NumberFormat('ja-JP').format(v)}
function save(){state.version=V;state.updatedAt=new Date().toISOString();localStorage.setItem(K,JSON.stringify(state))}
function load(){try{const r=localStorage.getItem(K);return r?migrate(JSON.parse(r)):base()}catch{return base()}}
function club(v){const s=t(v);if(/carrot|キャロット/i.test(s))return'キャロット';if(/silk|シルク/i.test(s))return'シルク';if(/union|ユニオン/i.test(s))return'ユニオン';return s||'その他'}
function sex(v){const s=t(v);if(/牡|male|colt/i.test(s))return'牡';if(/牝|female|filly/i.test(s))return'牝';if(/せん|騸|gelding/i.test(s))return'せん';return s}
function area(v){const s=t(v);if(/美浦/.test(s))return'美浦';if(/栗東/.test(s))return'栗東';if(/地方/.test(s))return'地方';return s}
function migrate(x){if(Array.isArray(x))x={horses:x};const a=x?.horses||x?.records||x?.items||(x?.horseName?[x]:[]);return{version:V,app:'Horse Evaluator',updatedAt:new Date().toISOString(),horses:a.map((h,i)=>{const m=h.measurements||{};const now=new Date().toISOString();return{id:h.id||uid(),year:Number(h.year||h.recruitmentYear||new Date().getFullYear()),club:club(h.club),horseNo:n(h.horseNo??h.number),name:t(h.name||h.horseName||`名称未設定 ${i+1}`),sex:sex(h.sex),birthDate:t(h.birthDate),sire:t(h.sire||h.father),dam:t(h.dam||h.mother),broodmareSire:t(h.broodmareSire||h.damsire),stableArea:area(h.stableArea||h.affiliation||h.region),trainer:t(h.trainer||h.stable),breeder:t(h.breeder||h.farm),trainingFarm:t(h.trainingFarm),price:n(h.price||h.totalPrice),sharePrice:n(h.sharePrice||h.unitPrice),measurements:{weight:n(m.weight??m.bodyWeight??h.weight),height:n(m.height??h.height),girth:n(m.girth??m.chest??h.girth),cannon:n(m.cannon??m.cannonBone??h.cannon)},sourceUrl:t(h.sourceUrl||h.pageUrl),photoUrl:t(h.photoUrl||h.photo||h.files?.photo),videoUrl:t(h.videoUrl||h.video||h.files?.video),favorite:Boolean(h.favorite),notes:t(h.notes||h.memo),createdAt:h.createdAt||now,updatedAt:h.updatedAt||h.createdAt||now,changeLog:Array.isArray(h.changeLog)?h.changeLog:[{at:h.createdAt||now,action:'移行・登録'}]}})}}
function toast(s){E.toast.textContent=s;E.toast.classList.add('show');clearTimeout(toast.x);toast.x=setTimeout(()=>E.toast.classList.remove('show'),1800)}
function refreshFilters(){const y=E.yearFilter.value,c=E.clubFilter.value,ys=[...new Set(state.horses.map(h=>h.year))].sort((a,b)=>b-a),cs=[...new Set(state.horses.map(h=>h.club))].sort();E.yearFilter.innerHTML='<option value="">すべて</option>'+ys.map(v=>`<option>${v}</option>`).join('');E.clubFilter.innerHTML='<option value="">すべて</option>'+cs.map(v=>`<option>${esc(v)}</option>`).join('');if(ys.map(String).includes(y))E.yearFilter.value=y;if(cs.includes(c))E.clubFilter.value=c}
function list(){const y=E.yearFilter.value,c=E.clubFilter.value,a=E.stableAreaFilter.value,q=E.searchInput.value.toLowerCase(),fav=E.favoriteOnly.checked,s=E.sortSelect.value;return state.horses.filter(h=>(!y||String(h.year)===y)&&(!c||h.club===c)&&(!a||h.stableArea===a)&&(!fav||h.favorite)&&(!q||[h.name,h.sire,h.dam,h.broodmareSire,h.stableArea,h.trainer,h.breeder,h.trainingFarm,h.notes].join(' ').toLowerCase().includes(q))).sort((x,z)=>s==='updatedAt'?new Date(z.updatedAt)-new Date(x.updatedAt):s==='name'?x.name.localeCompare(z.name,'ja'):s==='price'?(z.price||0)-(x.price||0):(x.horseNo??9999)-(z.horseNo??9999))}
function metric(l,v,u){return`<div class="metric"><b>${v==null?'―':esc(v)}</b><span>${l}${v==null?'':' '+u}</span></div>`}
function card(h){const m=h.measurements||{},bg=h.photoUrl?`style="background-image:url('${esc(h.photoUrl)}')"`:'';return`<article class="horse-card"><div class="photo" ${bg}>${h.photoUrl?'':'NO PHOTO'}</div><div class="body"><div class="topline"><div><span class="badge">${h.year} ${esc(h.club)}</span>${h.horseNo!=null?`<span class="badge">No.${h.horseNo}</span>`:''}${h.stableArea?`<span class="badge">${esc(h.stableArea)}</span>`:''}<h3>${esc(h.name)}</h3></div><button class="favorite ${h.favorite?'on':''}" data-a="favorite" data-id="${h.id}">★</button></div><div class="pedigree">父：${esc(h.sire)||'―'}<br>母：${esc(h.dam)||'―'}<br>母父：${esc(h.broodmareSire)||'―'}<br>厩舎：${esc(h.trainer)||'―'}</div><div class="price-box"><b>総額 ${h.price==null?'―':money(h.price)+'万円'}</b><span>1口 ${h.sharePrice==null?'―':money(h.sharePrice)+'円'}</span></div><div class="metrics">${metric('体重',m.weight,'kg')}${metric('体高',m.height,'cm')}${metric('胸囲',m.girth,'cm')}${metric('管囲',m.cannon,'cm')}</div><div class="card-actions"><button data-a="detail" data-id="${h.id}">詳細</button><button data-a="edit" data-id="${h.id}">編集</button><button data-a="delete" data-id="${h.id}" class="danger">削除</button></div><div class="updated">更新：${fmt(h.updatedAt)}</div></div></article>`}
function render(){refreshFilters();const a=list();E.dashboard.innerHTML=[['登録頭数',state.horses.length],['年度数',new Set(state.horses.map(h=>h.year)).size],['クラブ数',new Set(state.horses.map(h=>h.club)).size],['お気に入り',state.horses.filter(h=>h.favorite).length]].map(([l,v])=>`<div class="stat"><div class="num">${v}</div><div class="label">${l}</div></div>`).join('');E.resultCount.textContent=`${a.length}頭`;E.horseList.innerHTML=a.map(card).join('');E.emptyState.classList.toggle('hidden',a.length!==0)}
function setImportStatus(msg,type=''){E.importStatus.textContent=msg;E.importStatus.className='muted '+(type==='ok'?'import-status-ok':type==='error'?'import-status-error':'')}
function openNew(){E.horseForm.reset();$('horseId').value='';$('year').value=new Date().getFullYear();$('dialogTitle').textContent='新規登録';setImportStatus('');E.horseDialog.showModal()}
function openEdit(id){const h=state.horses.find(x=>x.id===id);if(!h)return;['year','club','horseNo','name','sex','birthDate','sire','dam','broodmareSire','stableArea','trainer','breeder','trainingFarm','price','sharePrice','sourceUrl','photoUrl','videoUrl','notes'].forEach(k=>$(k).value=h[k]??'');['weight','height','girth','cannon'].forEach(k=>$(k).value=h.measurements?.[k]??'');$('favorite').checked=h.favorite;$('horseId').value=h.id;$('dialogTitle').textContent='募集馬を編集';setImportStatus('');E.horseDialog.showModal()}
function readForm(){const id=$('horseId').value||uid(),old=state.horses.find(h=>h.id===id),now=new Date().toISOString();return{id,year:Number($('year').value),club:$('club').value,horseNo:n($('horseNo').value),name:t($('name').value),sex:$('sex').value,birthDate:$('birthDate').value,sire:t($('sire').value),dam:t($('dam').value),broodmareSire:t($('broodmareSire').value),stableArea:$('stableArea').value,trainer:t($('trainer').value),breeder:t($('breeder').value),trainingFarm:t($('trainingFarm').value),price:n($('price').value),sharePrice:n($('sharePrice').value),measurements:{weight:n($('weight').value),height:n($('height').value),girth:n($('girth').value),cannon:n($('cannon').value)},sourceUrl:t($('sourceUrl').value),photoUrl:t($('photoUrl').value),videoUrl:t($('videoUrl').value),favorite:$('favorite').checked,notes:t($('notes').value),createdAt:old?.createdAt||now,updatedAt:now,changeLog:[...(old?.changeLog||[]),{at:now,action:old?'更新':'登録'}]}}
function detail(id){const h=state.horses.find(x=>x.id===id),m=h.measurements||{},d=(l,v)=>`<div class="detail-item"><span>${l}</span><b>${esc(v)||'―'}</b></div>`;E.detailContent.innerHTML=`<div class="dialog-head"><div><div class="eyebrow">${h.year} ${esc(h.club)} ${h.horseNo!=null?'No.'+h.horseNo:''}</div><h2>${esc(h.name)}</h2></div></div>${h.photoUrl?`<div class="detail-photo" style="background-image:url('${esc(h.photoUrl)}')"></div>`:''}<div class="detail-grid">${d('性別',h.sex)}${d('生年月日',h.birthDate)}${d('父',h.sire)}${d('母',h.dam)}${d('母父',h.broodmareSire)}${d('所属',h.stableArea)}${d('厩舎',h.trainer)}${d('生産牧場',h.breeder)}${d('育成牧場',h.trainingFarm)}${d('募集総額',h.price==null?'':money(h.price)+'万円')}${d('1口価格',h.sharePrice==null?'':money(h.sharePrice)+'円')}${d('馬体重',m.weight==null?'':m.weight+'kg')}${d('体高',m.height==null?'':m.height+'cm')}${d('胸囲',m.girth==null?'':m.girth+'cm')}${d('管囲',m.cannon==null?'':m.cannon+'cm')}</div>${h.sourceUrl?`<a class="source-link" href="${esc(h.sourceUrl)}" target="_blank" rel="noopener">募集馬ページを開く</a>`:''}${h.videoUrl?`<p><a href="${esc(h.videoUrl)}" target="_blank" rel="noopener">歩様動画を開く</a></p>`:''}<h3>メモ</h3><div class="notes">${esc(h.notes)||'―'}</div><h3>更新履歴</h3><div class="notes">${(h.changeLog||[]).slice().reverse().map(x=>fmt(x.at)+'　'+esc(x.action)).join('\n')}</div>`;E.detailDialog.showModal()}
function cleanText(s){return t(s).replace(/\u00a0/g,' ').replace(/[ \t]+/g,' ').replace(/\r/g,'')}
function first(text,re,group=1){const m=text.match(re);return m?t(m[group]):''}
function numberFrom(text,re){const s=first(text,re).replace(/,/g,'');return s?Number(s):null}
function parseUnion(text,url){const x=cleanText(text),main=(x.match(/測尺[\s\S]*?(?:募集時のPR|ポイント)/)||['',x])[0];const weights=[...main.matchAll(/馬体重[：:\s]*([0-9.]+)\s*kg/g)].map(m=>Number(m[1]));const nameCandidates=[...x.matchAll(/([^\s|｜<>]{1,30}の20\d{2})/g)].map(m=>m[1]).filter(v=>!/募集|年齢/.test(v));const birth=first(x,/生年月日\s*([0-9]{4})[\/.-]([0-9]{1,2})[\/.-]([0-9]{1,2})/,0);let birthDate='';if(birth){const p=birth.match(/([0-9]{4})[\/.-]([0-9]{1,2})[\/.-]([0-9]{1,2})/);birthDate=`${p[1]}-${p[2].padStart(2,'0')}-${p[3].padStart(2,'0')}`}
const year=numberFrom(x,/〖(20\d{2})年(?:5月下旬|7月上旬)/)||new Date().getFullYear();
return{year,club:'ユニオン',horseNo:numberFrom(x,/PEGASUS\s*([0-9]+)/i),name:nameCandidates[0]||'',sex:first(x,/性別\s*(牡|牝|せん|騸)/),birthDate,sire:first(x,/父\s+([^\n]+?)(?=\s+母\s|\n)/),dam:first(x,/母\s+([^\n]+?)(?=\s+母の父|\n)/).replace(/^\*/,'').trim(),broodmareSire:first(x,/母の父\s+([^\n]+?)(?=\s+5代血統表|\s+生年月日|\n)/).replace(/^\*/,'').trim(),stableArea:first(x,/所属\s*(美浦|栗東|地方)/),trainer:first(x,/(?:予定厩舎|厩舎)\s*([^\n]+?)(?=\s+測尺|\n)/).replace(/厩舎$/,''),breeder:first(x,/生産[：:]\s*([^\n]+)/).replace(/\s+(所属|予定厩舎).*$/,''),price:numberFrom(x,/総額\s*([0-9,]+)万円/),sharePrice:numberFrom(x,/一口価格\s*([0-9,]+)円/),measurements:{weight:weights.length?weights[weights.length-1]:numberFrom(x,/馬体重[：:\s]*([0-9.]+)\s*kg/),height:numberFrom(main,/体高[：:\s]*([0-9.]+)\s*cm/),girth:numberFrom(main,/胸囲[：:\s]*([0-9.]+)\s*cm/),cannon:numberFrom(main,/管囲[：:\s]*([0-9.]+)\s*cm/)},sourceUrl:url}}
async function fetchPageText(url){let lastError;try{const r=await fetch(url,{mode:'cors',credentials:'omit'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const html=await r.text();return new DOMParser().parseFromString(html,'text/html').body?.innerText||html}catch(e){lastError=e}try{const clean=url.replace(/^https?:\/\//,'');const proxy=`https://r.jina.ai/https://${clean}`;const r=await fetch(proxy,{headers:{Accept:'text/plain'}});if(!r.ok)throw new Error(`Reader HTTP ${r.status}`);return await r.text()}catch(e){console.error(lastError,e);throw new Error('ページを取得できませんでした。通信状態または外部取得サービスの制限を確認してください。')}}
function applyImported(d){const fields=['year','club','horseNo','name','sex','birthDate','sire','dam','broodmareSire','stableArea','trainer','breeder','price','sharePrice','sourceUrl'];fields.forEach(k=>{if(d[k]!==''&&d[k]!=null)$(k).value=d[k]});['weight','height','girth','cannon'].forEach(k=>{if(d.measurements?.[k]!=null)$(k).value=d.measurements[k]})}
async function importFromUrl(){const url=t($('sourceUrl').value);if(!url){setImportStatus('URLを入力してください。','error');return}let u;try{u=new URL(url)}catch{setImportStatus('URLの形式を確認してください。','error');return}if(!/(^|\.)union-oc\.co\.jp$/i.test(u.hostname)){setImportStatus('Sprint 1.2はユニオン募集馬ページ専用です。','error');return}E.importUrlBtn.disabled=true;setImportStatus('ページを取得しています…');try{const text=await fetchPageText(u.origin+u.pathname+u.search);const d=parseUnion(text,url);const count=[d.horseNo,d.name,d.sire,d.dam,d.trainer,d.price,d.sharePrice,d.measurements.weight].filter(v=>v!==''&&v!=null).length;if(count<5)throw new Error('必要な項目を十分に抽出できませんでした。');applyImported(d);setImportStatus(`${count}項目を取得しました。内容を確認して保存してください。`,'ok');toast('ユニオン基本情報を取得しました')}catch(e){console.error(e);setImportStatus(e.message||'自動取込に失敗しました。','error')}finally{E.importUrlBtn.disabled=false}}
function exportJ(){const b=new Blob([JSON.stringify({...state,version:V,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=`horse-evaluator-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(u);toast('バックアップを書き出しました')}
async function importJ(f){try{const m=migrate(JSON.parse(await f.text()));if(!m.horses.length)throw 0;if(confirm(`${m.horses.length}頭を現在のデータに追加しますか？\nキャンセルすると置換します。`)){const map=new Map(state.horses.map(h=>[h.id,h]));m.horses.forEach(h=>map.set(h.id,h));state.horses=[...map.values()]}else state=m;save();render();toast(`${m.horses.length}頭を復元しました`)}catch{alert('JSONを読み込めませんでした。')}}
$('newHorseBtn').onclick=openNew;$('closeDialogBtn').onclick=$('cancelBtn').onclick=()=>E.horseDialog.close();$('detailCloseBtn').onclick=()=>E.detailDialog.close();E.importUrlBtn.onclick=importFromUrl;
E.horseForm.onsubmit=e=>{e.preventDefault();const h=readForm(),i=state.horses.findIndex(x=>x.id===h.id);i>=0?state.horses[i]=h:state.horses.push(h);save();E.horseDialog.close();render();toast(i>=0?'更新しました':'登録しました')};
[E.yearFilter,E.clubFilter,E.stableAreaFilter,E.sortSelect,E.favoriteOnly].forEach(x=>x.onchange=render);E.searchInput.oninput=render;
E.horseList.onclick=e=>{const b=e.target.closest('[data-a]');if(!b)return;const h=state.horses.find(x=>x.id===b.dataset.id);if(b.dataset.a==='edit')openEdit(h.id);if(b.dataset.a==='detail')detail(h.id);if(b.dataset.a==='favorite'){h.favorite=!h.favorite;h.updatedAt=new Date().toISOString();save();render()}if(b.dataset.a==='delete'&&confirm(`「${h.name}」を削除しますか？`)){state.horses=state.horses.filter(x=>x.id!==h.id);save();render()}};
$('exportBtn').onclick=exportJ;$('importInput').onchange=e=>{if(e.target.files[0])importJ(e.target.files[0]);e.target.value=''};
$('seedBtn').onclick=()=>{const now=new Date().toISOString();state.horses.push({id:uid(),year:2026,club:'ユニオン',horseNo:14,name:'リフレイムの2025',sex:'牝',birthDate:'2025-03-29',sire:'エピファネイア',dam:'リフレイム',broodmareSire:'アメリカンファラオ',stableArea:'美浦',trainer:'黒岩陽一',breeder:'千里ファーム',trainingFarm:'山口ステーブル',price:8800,sharePrice:110000,measurements:{weight:436,height:150,girth:172,cannon:20.5},sourceUrl:'https://www.union-oc.co.jp/id/4014#open_PHOTO',photoUrl:'',videoUrl:'',favorite:false,notes:'Sprint 1.2動作確認用',createdAt:now,updatedAt:now,changeLog:[{at:now,action:'サンプル登録'}]});save();render();toast('サンプルを追加しました')};
$('clearBtn').onclick=()=>{if(confirm('全データを削除しますか？')){state=base();save();render()}};render();})();
